name: "CI CD Pipeline for Auth Frontend Preprod"

on:
  workflow_dispatch:

jobs:
  cicd:
    runs-on: ubuntu-latest
    environment: preprod
    steps:
      - name: "Setup Nodejs"
        uses: actions/setup-node@v4
        with:
          node-version: "21"
      - name: "Check node installation"
        run: |
          node --version
          npm --version
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Install dependencies"
        run: npm install

      - name: "Install vercel cli"
        run: npm install --g vercel
      - name: "List directories"
        run: ls
      - name: "Run eslint"
        run: npm run lint
      - name: "Build"
        run: npm run build

      - name: "Deploy"
        run: vercel --prod --token ${{ secrets.TEMP_TOKEN }} --confirm --name=auth-frontend-preprod
